# Copyright (C) 2013 - Zhongnan Xu
"""This module contains the names of all of the psuedo potential files one
needs to use. If you wish to change the directory the files are found in,
edit the ESPRESSORC dictionary file found in espressorc.py
"""

ESPRESSO_PPs = {'Ag': ('ag_pbe_v1.uspp.F.UPF', 20),
                'Al': ('al_pbe_v1.uspp.F.UPF', 3),
                'As': ('as_pbe_v1.uspp.F.UPF', 5),
                'Au': ('au_pbe_v1.uspp.F.UPF', 11),
                'Ba': ('ba_pbe_v1.uspp.F.UPF', 10),
                'Be': ('be_pbe_v1.2.uspp.F.UPF', 4),
                'Bi': ('bi_pbe_v1.uspp.F.UPF', 14),
                'B': ('b_pbe_v1.01.uspp.F.UPF', 3),
                'Br': ('br_pbe_v1.uspp.F.UPF', 7),
                'Ca': ('ca_pbe_v1.uspp.F.UPF', 10),
                'Cd': ('cd_pbe_v1.uspp.F.UPF', 11),
                'Cl': ('cl_pbe_v1.2.uspp.F.UPF', 7),
                'Co': ('co_pbe_v1.2.uspp.F.UPF', 16),
                'C': ('c_pbe_v1.2.uspp.F.UPF', 4),
                'Cr': ('cr_pbe_v1.2.uspp.F.UPF', 13),
                'Cs': ('cs_pbe_v1.uspp.F.UPF', 9),
                'Cu': ('cu_pbe_v1.2.uspp.F.UPF', 18),
                'Fe': ('fe_pbe_v1.2.uspp.F.UPF', 15),
                'F': ('f_pbe_v1.2.uspp.F.UPF', 7),
                'Ga': ('ga_pbe_v1.uspp.F.UPF', 20),
                'Ge': ('ge_pbe_v1.uspp.F.UPF', 14),
                'Hf': ('hf_pbe_v1.uspp.F.UPF', 10), #'hf_pbe_plus4_v1.uspp.F.UPF' alt
                'Hg': ('hg_pbe_v1.uspp.F.UPF', 12),
                'H': ('h_pbe_v1.uspp.F.UPF', 1),
                'In': ('in_pbe_v1.uspp.F.UPF', 11),
                'I': ('i_pbe_v1.uspp.F.UPF', 7),
                'Ir': ('ir_pbe_v1.2.uspp.F.UPF', 15),
                'K': ('k_pbe_v1.uspp.F.UPF', 8),
                'La': ('la_pbe_v1.uspp.F.UPF', 11),
                'Li': ('li_pbe_v1.uspp.F.UPF', 3),
                'Mg': ('mg_pbe_v1.uspp.F.UPF', 10),
                'Mn': ('mn_pbe_v1.2.uspp.F.UPF', 14),
                'Mo': ('mo_pbe_v1.uspp.F.UPF', 14),
                'Na': ('na_pbe_v1.uspp.F.UPF', 9),
                'Nb': ('nb_pbe_v1.uspp.F.UPF', 13),
                'Ni': ('ni_pbe_v1.2.uspp.F.UPF', 16),
                'N': ('n_pbe_v1.2.uspp.F.UPF', 5),
                'O': ('o_pbe_v1.2.uspp.F.UPF', 6),
                'Os': ('os_pbe_v1.2.uspp.F.UPF', 16),
                'Pb': ('pb_pbe_v1.uspp.F.UPF', 14),
                'Pd': ('pd_pbe_v1.2.uspp.F.UPF', 16),
                'P': ('p_pbe_v1.uspp.F.UPF', 5),
                'Pt': ('pt_pbe_v1.uspp.F.UPF', 16),
                'Rb': ('rb_pbe_v1.uspp.F.UPF', 9),
                'Re': ('re_pbe_v1.2.uspp.F.UPF', 15),
                'Rh': ('rh_pbe_v1.2.uspp.F.UPF', 15),
                'Ru': ('ru_pbe_v1.2.uspp.F.UPF', 15),
                'Sb': ('sb_pbe_v1.uspp.F.UPF', 14),
                'Sc': ('sc_pbe_v1.uspp.F.UPF', 11),
                'Se': ('se_pbe_v1.uspp.F.UPF', 6),
                'Si': ('si_pbe_v1.uspp.F.UPF', 4),
                'Sn': ('sn_pbe_v1.uspp.F.UPF', 13),
                'S': ('s_pbe_v1.2.uspp.F.UPF', 6),
                'Sr': ('sr_pbe_v1.uspp.F.UPF', 10),
                'Ta': ('ta_pbe_v1.uspp.F.UPF', 13),
                'Tc': ('tc_pbe_v1.uspp.F.UPF', 14),
                'Te': ('te_pbe_v1.uspp.F.UPF', 6),
                'Ti': ('ti_pbe_v1.uspp.F.UPF', 11),
                'Tl': ('tl_pbe_v1.2.uspp.F.UPF', 13),
                'V': ('v_pbe_v1.uspp.F.UPF', 13),
                'W': ('w_pbe_v1.2.uspp.F.UPF', 14),
                'Y': ('y_pbe_v1.uspp.F.UPF', 11),
                'Zn': ('zn_pbe_v1.uspp.F.UPF', 20),
                'Zr': ('zr_pbe_v1.uspp.F.UPF', 12)}

gbrv_v101 = {'Ag': ('ag_pbe_v1.uspp.F.UPF', 20),
             'Al': ('al_pbe_v1.uspp.F.UPF', 3),
             'As': ('as_pbe_v1.uspp.F.UPF', 5),
             'Au': ('au_pbe_v1.uspp.F.UPF', 11),
             'Ba': ('ba_pbe_v1.uspp.F.UPF', 10),
             'Be': ('be_pbe_v1.uspp.F.UPF', 4),
             'Bi': ('bi_pbe_v1.uspp.F.UPF', 14),
             'B': ('b_pbe_v1.01.uspp.F.UPF', 3),
             'Br': ('br_pbe_v1.uspp.F.UPF', 7),
             'Ca': ('ca_pbe_v1.uspp.F.UPF', 10),
             'Cd': ('cd_pbe_v1.uspp.F.UPF', 11),
             'Cl': ('cl_pbe_v1.uspp.F.UPF', 7),
             'Co': ('co_pbe_v1.uspp.F.UPF', 16),
             'C': ('c_pbe_v1.01.uspp.F.UPF', 4),
             'Cr': ('cr_pbe_v1.uspp.F.UPF', 13),
             'Cs': ('cs_pbe_v1.uspp.F.UPF', 9),
             'Cu': ('cu_pbe_v1.uspp.F.UPF', 19),
             'Fe': ('fe_pbe_v1.uspp.F.UPF', 16),
             'F': ('f_pbe_v1.uspp.F.UPF', 7),
             'Ga': ('ga_pbe_v1.uspp.F.UPF', 20),
             'Ge': ('ge_pbe_v1.uspp.F.UPF', 14),
             'Hf': ('hf_pbe_v1.uspp.F.UPF', 10), #'hf_pbe_plus4_v1.uspp.F.UPF' alt
             'Hg': ('hg_pbe_v1.uspp.F.UPF', 12),
             'H': ('h_pbe_v1.uspp.F.UPF', 1),
             'In': ('in_pbe_v1.uspp.F.UPF', 11),
             'I': ('i_pbe_v1.uspp.F.UPF', 7),
             'Ir': ('ir_pbe_v1.uspp.F.UPF', 15),
             'K': ('k_pbe_v1.uspp.F.UPF', 8),
             'La': ('la_pbe_v1.uspp.F.UPF', 11),
             'Li': ('li_pbe_v1.uspp.F.UPF', 3),
             'Mg': ('mg_pbe_v1.uspp.F.UPF', 10),
             'Mn': ('mn_pbe_v1.uspp.F.UPF', 15),
             'Mo': ('mo_pbe_v1.uspp.F.UPF', 14),
             'Na': ('na_pbe_v1.uspp.F.UPF', 9),
             'Nb': ('nb_pbe_v1.uspp.F.UPF', 13),
             'Ni': ('ni_pbe_v1.uspp.F.UPF', 18),
             'N': ('n_pbe_v1.01.uspp.F.UPF', 5),
             'O': ('o_pbe_v1.01.uspp.F.UPF', 6),
             'Os': ('os_pbe_v1.uspp.F.UPF', 16),
             'Pb': ('pb_pbe_v1.uspp.F.UPF', 14),
             'Pd': ('pd_pbe_v1.uspp.F.UPF', 16),
             'P': ('p_pbe_v1.uspp.F.UPF', 5),
             'Pt': ('pt_pbe_v1.uspp.F.UPF', 16),
             'Rb': ('rb_pbe_v1.uspp.F.UPF', 9),
             'Re': ('re_pbe_v1.uspp.F.UPF', 15),
             'Rh': ('rh_pbe_v1.uspp.F.UPF', 15),
             'Ru': ('ru_pbe_v1.uspp.F.UPF', 16),
             'Sb': ('sb_pbe_v1.uspp.F.UPF', 14),
             'Sc': ('sc_pbe_v1.uspp.F.UPF', 11),
             'Se': ('se_pbe_v1.uspp.F.UPF', 6),
             'Si': ('si_pbe_v1.uspp.F.UPF', 4),
             'Sn': ('sn_pbe_v1.uspp.F.UPF', 13),
             'S': ('s_pbe_v1.uspp.F.UPF', 6),
             'Sr': ('sr_pbe_v1.uspp.F.UPF', 10),
             'Ta': ('ta_pbe_v1.uspp.F.UPF', 13),
             'Tc': ('tc_pbe_v1.uspp.F.UPF', 14),
             'Te': ('te_pbe_v1.uspp.F.UPF', 6),
             'Ti': ('ti_pbe_v1.uspp.F.UPF', 11),
             'Tl': ('tl_pbe_v1.uspp.F.UPF', 13),
             'V': ('v_pbe_v1.uspp.F.UPF', 13),
             'W': ('w_pbe_v1.uspp.F.UPF', 14),
             'Y': ('y_pbe_v1.uspp.F.UPF', 11),
             'Zn': ('zn_pbe_v1.uspp.F.UPF', 20),
             'Zr': ('zr_pbe_v1.uspp.F.UPF', 12)}

QE_PSEUDO = {'Ag':('Ag.pbe-d-rrkjus.UPF', 11),
             'Be':('Be.pbe-rrkjus.UPF', 2),
             'Co':('Co.pbe-nd-rrkjus.UPF', 9),
             'C' :('C.pbe-rrkjus.UPF', 4),
             'Cr':('Cr.pbe-sp-van.UPF', 14),
             'Cu':('Cu.pbe-n-van_ak.UPF', 11),
             'Fe':('Fe.pbe-nd-rrkjus.UPF', 8),
             'H' :('H.pbe-rrkjus.UPF', 1),
             'Ir':('Ir.pbe-n-rrkjus.UPF', 9),
             'Li':('Li.pbe-n-van.UPF', 1),
             'Mn':('Mn.pbe-sp-van.UPF', 15),
             'Mo':('Mo.pbe-spn-rrkjus_psl.0.2.UPF', 14),
             'Nb':('Nb.pbe-nsp-van.UPF', 13),
             'Ni':('Ni.pbe-nd-rrkjus.UPF', 10),
             'N' :('N.pbe-rrkjus.UPF', 5),
             'O' :('O.pbe-rrkjus.UPF', 6),
             'S' :('S.pbe-van_bm.UPF', 6),
             'Os':('Os.pbe-n-van.UPF', 8),
             'Pd':('Pd.pbe-n-rrkjus_psl.0.2.2.UPF', 10),
             'Pt':('Pt.pbe-nd-rrkjus.UPF', 10), # alt Pt.pbe-n-van.UPF
             'Rh':('Rh.pbe-nd-rrkjus.UPF', 9),
             'Ru':('Ru.pbe-n-van.UPF', 8),
             'Ta':('Ta.pbe-nsp-van.UPF', 13),
             'Ti':('Ti.pbe-sp-van_ak.UPF', 12),
             'V' :('V.pbe-n-van.UPF', 5),
             'W' :('W.pbe.nsp-van.UPF', 14),
             'Zr':('Zr.pbe-nsp-van.UPF', 12)}
